### ISSUE TITLE
Program Graph metamodel

### ISSUE THREAD

**Issue by tsdh** [Echtzeitsysteme/java-refactoring-ttc#1]
Currently, the repository doesn't seem to contain the metamodel from Figure 2 in the case description, i.e., the type graph with all the `T*` classes.  Will that be added or are solution authors supposed to recreate it themselves?

**Comment by SvenPeldszus** [comment]
The model got somehow lost, but now I've added it to the ecore folder.

**Comment by tsdh** [comment]
Thanks!
