### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by szarnyasg** [Echtzeitsysteme/java-refactoring-ttc#15]
I discovered some minor typos in the paper:
- apreasumed
- accoring
- transformatio,
- some "etc."-s are missing a comma
- fulfil
- "the classes either has to have the same"

Gabor

**Comment by tsdh** [comment]
And "Extendability" is no English word (extensibility).

**Comment by gkulcsar** [comment]
Thank you for the feedback and excuse me for the delay - an updated version of the case description without (some of the most annoying) typos is now submitted.
