### ISSUE TITLE
Cannot execute one test

### ISSUE THREAD

**Issue by GerardPaligot** [Echtzeitsysteme/java-refactoring-ttc#16]
I would like to execute only one test with the command line:

``` console
execute −−test public_pum_1.ttc pub_pum1_1_paper1
```

But ARTE tell me that:

``` console
Possible arguments are "--test", "--hidden", "--all", and "--help".
```

**Comment by SvenPeldszus** [comment]
At a first sight the minus signs in the command entered by you seem to be longer than the ones displayed in the help text. If this are really different chars ARTE will not accept them.

In the command entered by you, you will not just execute a single test case. You are going to execute the test case "pub_pum1_1_paper1" and all test cases contained in the file "public_pum_1.ttc".

**Comment by GerardPaligot** [comment]
> At a first sight the minus signs in the command entered by you seem to be longer than the ones displayed in the help text. If this are really different chars ARTE will not accept them.

Ok, I don't know why but it works now. Thanks.

> In the command entered by you, you will not just execute a single test case. You are going to execute the test case "pub_pum1_1_paper1" and all test cases contained in the file "public_pum_1.ttc".

Ok. So, `execute −−test pub_pum1_1_paper1` is the command I searched. Thanks!

So I close this issue.
