### ISSUE TITLE
Cannot execute hidden test

### ISSUE THREAD

**Issue by GerardPaligot** [Echtzeitsysteme/java-refactoring-ttc#20]
When I would like to execute a hidden test, I got a `NullPointerException`:

``` console
ERROR: Unhandled runtime exception
java.lang.NullPointerException
    at arte.execution.TestExecution.executeTestByName(TestExecution.java:99)
    at arte.shell.commands.impl.ExecuteTestCommand.execute(ExecuteTestCommand.java:89)
    at arte.shell.Shell.executeCommand(Shell.java:100)
    at arte.shell.Shell.shell(Shell.java:57)
    at arte.Arte.main(Arte.java:96)
```

**Comment by SvenPeldszus** [comment]
I cannot reproduce the failure at my system.

At the point the Nullpointer Exception occurs the test cases are loaded from the file system. 

Which test cannot be loaded?
Are other hidden test cases successful loaded?

You can try to delete in the ARTE folder the folder "data_private" and replace it with the latest from the repository.

**Comment by GerardPaligot** [comment]
> Which test cannot be loaded?

All hidden tests.

> You can try to delete in the ARTE folder the folder "data_private" and replace it with the latest from the repository.

I'm up-to-date with the repo.

**Comment by SvenPeldszus** [comment]
I added a workaround which catches the null pointer exception. however this exception should not be thrown. Hopefully you are now able to execute at least some of the hidden test cases until I provide a new patch.

Therefore I need some more information.

1) On which operating system are you executing ARTE?
2) What does "testcases --list" return?
3) Do you always exit ARTE with "exit"?
4) Have you tried to copy ARTE to a different location in your file system?
5) Is in the new version any hidden test case executed?

**Comment by GerardPaligot** [comment]
Did you make something with the last version of ARTE? Now, I have the message:

``` console
There is no test case "hidden_csc1_1" in the test suite.
```

> 1) On which operating system are you executing ARTE?

OS X

> 2) What does "testcases --list" return?

``` console
testcases --list
The test suite currently contains 6 public accessible test cases.
    "pub_pum1_2" in test case file "public_pum_1.ttc" 
    "pub_pum1_1_paper1" in test case file "public_pum_1.ttc" 
    "pub_exs1_2" in test case file "public_exs_1.ttc" 
    "pub_exs1_1" in test case file "public_exs_1.ttc" 
    "pub_pum3_1" in test case file "public_pum_3.ttc" 
    "pub_pum2_1" in test case file "public_pum_2.ttc" 
```

So, it isn't possible to execute one hidden test case but I can execute them when I execute all tests? It is weird.

> 3) Do you always exit ARTE with "exit"?

Yes.

> 4) Have you tried to copy ARTE to a different location in your file system?

No.

> 5) Is in the new version any hidden test case executed?

No, see the top of this message.

**Comment by SvenPeldszus** [comment]
> Did you make something with the last version of ARTE? Now, I have the message:

Yes, I added a null check and Prinz the key oft the test case.

As the keys are derived from the found hidden test case files and not hard coded, I expected that on your system the files are not found at all and ARTE tries to execute a test case with null or empty String as name.

> > 2) What does "testcases --list" return?

Is there really no line aftwrwards with the amount of hidden test cases. Even if no hidden case is found this shoulb be printed

> So, it isn't possible to execute one hidden test case but I can execute them when I execute all tests? It is weird.

That is really wird, as in execute all execute hidden is called.

I am still on it and will fix it as soon as possible.

**Comment by GerardPaligot** [comment]
Oh, sorry ! I forgot the last line in the command result:

``` console
testcases --list
The test suite currently contains 6 public accessible test cases.
    "pub_pum1_2" in test case file "public_pum_1.ttc" 
    "pub_pum1_1_paper1" in test case file "public_pum_1.ttc" 
    "pub_exs1_2" in test case file "public_exs_1.ttc" 
    "pub_exs1_1" in test case file "public_exs_1.ttc" 
    "pub_pum3_1" in test case file "public_pum_3.ttc" 
    "pub_pum2_1" in test case file "public_pum_2.ttc" 
The test suite currently contains 9 hidden test cases.
```

But I cannot execute them.

**Comment by SvenPeldszus** [comment]
Ok, this fits to the behavior at test execution.

**Comment by GerardPaligot** [comment]
So it is wanted that we cannot execute them?

**Comment by SvenPeldszus** [comment]
It is wanted the you can execute them.

The cases are found in both variants but can somehow not be accessed.

**Comment by SvenPeldszus** [comment]
I still cannot reproduce this error. I thought this is a MAC related problem but on a MAC I borrowed me the execution of the test cases was possible.

Is it ok for you to execute the hidden test cases via `execute --all`.

**Comment by GerardPaligot** [comment]
> Is it ok for you to execute the hidden test cases via `execute --all`.

Yep, no problem.
