### ISSUE TITLE
Probably wrong assertion in pub_exs1_2

### ISSUE THREAD

**Issue by tsdh** [Echtzeitsysteme/java-refactoring-ttc#27]
This CSC refactoring wants to create a new class `example04.parent` (why not stick to Java naming conventions?) for the existing classes `ChildClass1` and `ChildClass2`.  These don't have a superclass yet.

So my transformation creates that new class and makes the two existing classes subclasses of that.  But I get the ARTE assertion error `FAILURE: Extension of "foo.Foo" expected but "example04.parent" has been extended. (false-negative)`.

**Comment by GerardPaligot** [comment]
The same for me.

**Comment by SvenPeldszus** [comment]
Oh, at this point the refactoring of  `pub_exs1_2` is called again instead of the desired one.

I've also renamed the class in `pub_exs1_1` to `Parent`

Also the test cases are now called `pub_csc1_1` and `pub_csc1_2`

**Comment by tsdh** [comment]
Ok, the new two tests work for me now.
