### ISSUE TITLE
PG metamodel, field types, and method parameter/return types

### ISSUE THREAD

**Issue by tsdh** [Echtzeitsysteme/java-refactoring-ttc#3]
The metamodel's `TSignature` subclasses reference `TClass` for method return and parameter types, and for field types.  Does that mean that (at least for the TTC case) there won't be any methods/fields that have a return/parameter/field type different than a class, e.g., no interfaces, primitives, or arrays?

**Comment by SvenPeldszus** [comment]
You are right interfaces and arrays are not supported as return values, parameters or field types.

For primitive types I suggest to handle them as classes from libraries. As we do not care about the instruction level and therefore not about the values of primitive types and there are no outgoing accesses this is a sufficient assumption.

Something similar have we done in the ARTE handbook in TestFile1.1 (line 20) for specifying test cases with primitive types in method signatures.

**Comment by tsdh** [comment]
Ok.
