### ISSUE TITLE
Extract superclass extension

### ISSUE THREAD

**Issue by tsdh** [Echtzeitsysteme/java-refactoring-ttc#31]
The case description's first extension task is to implement an extract superclass refactoring.  There is no signature defined for it in the case description, nor does a corresponding method in the `TestInterface` exist so I don't have a clue what its parameters should be.

I guess it should be something like `esc(classes, features, NewSuper)` where `classes` is a set of existing classes (which must have the same superclass or none), `features` is a set of field and method signatures (where the field type/method param types are just strings) that have to be declared for each class in `classes`, and `NewSuper` is the name of the new superclass.

Well, but it's your job to define the shape of a _full-fledged implementation which can be executed on an appropriate example program_ as the case description says.

**Comment by gkulcsar** [comment]
For the extensions, we intended not to provide any interfaces to implement them. This part of the challenge was meant to be rather freestyle. In an extreme case, an implementation of the Extract Superclass must not be compatible with ARTE anymore if it "gets the job done" in a comprehensible way.

**Comment by tsdh** [comment]
Ok, then I'll do it freestyle. :-)
