### ISSUE TITLE
ARTE: What's included in the printed execution times?

### ISSUE THREAD

**Issue by tsdh** [Echtzeitsysteme/java-refactoring-ttc#36]
When running solutions in ARTE, messages like

```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SUCCESS: Test case "hidden_csc3_1" has been executed SUCCESSFULLY.
The solution needed 0.015 seconds for execution. 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

are printed.  What's included in this execution time?  The sum of every `TestInterface` method execution time, only the execution time of the `apply*()` methods, or `createProgramGraph() + apply*() +  synchronizeChanges()`?

**Comment by SvenPeldszus** [comment]
The  execution time includes only `createProgramGraph()` + `apply*()` + `synchronizeChanges()`.

**Comment by tsdh** [comment]
Ok, that makes sense.
