### ISSUE TITLE
Contradictory cases: hidden_csc1_1 and hidden_csc1_2

### ISSUE THREAD

**Issue by steindani** [Echtzeitsysteme/java-refactoring-ttc#39]
I found the following two cases contradictory. If I check, whether the method to be pulled up into the new class accesses a local field and refuse to execute the transformation, the `hidden_csc1_1` test fails. If I allow it, the `hidden_csc1_2` test fails.

In the `hidden_csc1_1` test, The `ChildClass1` class has a field `field` and the method `method()` accesses it. The `ChildClass2` class does not have a field. Why should the transformation be executed?

**Comment by SvenPeldszus** [comment]
I think you performed an extract superclass refactoring.

The execution of the requested  create superclass refactoring only consists out of creating the superclass. A pull-up of a method is not requested.

**Comment by steindani** [comment]
Thanks for the quick reply! That makes sense. :)
