### ISSUE TITLE
Making the inheritance reference bidirectional

### ISSUE THREAD

**Issue by tsdh** [Echtzeitsysteme/java-refactoring-ttc#8]
Currently, the `inheritance` reference (which should actually be named `superclass`) is unidirectional.  A `TClass` references its superclass if it has one but there's no efficient way to get the subclasses of a given class.  But sadly, the refactorings pretty much depend on that.

Is it allowed to make that reference bidirectional or is that forbidden by _"It is not allowed to make additional information available in the PG."_ in the case description?  (I'd argue that this is no additional information but only a way to make existing information efficiently accessible.)

**Comment by SvenPeldszus** [comment]
Yes, I see that also not as additional information

I will include the bidirectional edge into the type graph so that everyone notices this.

**Comment by tsdh** [comment]
Perfect.
